# Generated by Django 5.2.17 on 2026-09-13 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditHead',
            fields=[
                ('chain', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('digest', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=300)),
                ('sequence', models.PositiveBigIntegerField()),
                ('payload', models.JSONField()),
                ('previous', models.CharField(max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chain', 'sequence'), name='audit_chain_sequence')],
            },
        ),
    ]
