# Generated by Django 5.2.17 on 2026-09-13 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('proposer', models.CharField(max_length=100)),
                ('approver', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('state', models.CharField(default='awaiting_approval', max_length=40)),
                ('error', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'proposer', 'idempotency_key'), name='change_idempotency')],
            },
        ),
    ]
