apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector: {app: {{ .Release.Name }}}
  ports: [{port: 8000, targetPort: 8000}]
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {app: {{ .Release.Name }}}
