# Generated by Django 5.2.17 on 2026-09-13 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('site', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=100)),
                ('epoch', models.PositiveIntegerField(default=1)),
                ('local', models.BooleanField(default=True)),
                ('connected', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('height_u', models.PositiveIntegerField(default=42)),
                ('budget_watts', models.PositiveIntegerField(default=8000)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('asset_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=100)),
                ('u', models.PositiveIntegerField()),
                ('height_u', models.PositiveIntegerField()),
                ('face', models.CharField(default='front', max_length=10)),
                ('owner', models.CharField(default='unum', max_length=100)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='placement.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('request_id', models.UUIDField(primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=100)),
                ('asset_id', models.CharField(max_length=100)),
                ('u', models.PositiveIntegerField()),
                ('height_u', models.PositiveIntegerField()),
                ('face', models.CharField(max_length=10)),
                ('expected_revision', models.PositiveIntegerField()),
                ('authority_epoch', models.PositiveIntegerField()),
                ('state', models.CharField(default='held', max_length=40)),
                ('expires_at', models.DateTimeField()),
                ('committed_revision', models.PositiveIntegerField(null=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='placement.rack')),
            ],
        ),
        migrations.AddField(
            model_name='rack',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='placement.room'),
        ),
    ]
