# Generated by Django 5.2.17 on 2026-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('room', 'Room'), ('data_hall', 'Data hall'), ('mdf', 'MDF'), ('idf', 'IDF')], default='room', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
