import {roomTypeLabel} from './LocationHierarchy';
import {Component,lazy,Suspense,useEffect,useMemo,useState,useRef} from 'react';
import type {ReactNode} from 'react';
import {Activity,ArrowDownUp,ArrowRight,Box,Check,ChevronDown,ChevronRight,CircleHelp,Clock,CloudOff,Cpu,Grid2X2,Layers,LayoutDashboard,Maximize2,Menu,Network,PanelRight,RefreshCw,Search,Server,Settings2,ShieldCheck,Sun,Thermometer,Undo2,Users,Workflow,Zap,X} from 'lucide-react';
import {api} from './api';
import LocationsHome from './LocationsHome';
import RackElevations from './RackElevations';
import ChangeCard from './ChangeCard';
import {validateGhost,cabinetSelection} from './domain';
import {useOperationsData} from './useOperationsData';
import {createMoveSubmission} from './moveSubmission';
import type {Asset,Change,Ghost,Overlay,Placement,Rack,View} from './types';
const Twin3D=lazy(()=>import('./Twin3D'));
const label=(s:string)=>s.replaceAll('_',' ');
class RenderBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<div className="empty">3D is unavailable. Use the 2D floor plan or rack elevation.</div>:this.props.children}}

function FloorPlan({roomType,racks,placements,assets,selected,onSelect,overlay,onDrop,ghost,search}:{roomType:string;racks:Rack[];placements:Placement[];assets:Asset[];selected:string[];onSelect:(id:string,toggle?:boolean,range?:boolean)=>void;overlay:Overlay;onDrop:(id:string,asset:string)=>void;ghost:Ghost|null;search:string}){
 return <svg className="floor-svg" viewBox="0 0 1050 660" role="group" aria-label={`${roomType} floor plan`}>
 <defs><pattern id="tiles" width="26" height="26" patternUnits="userSpaceOnUse"><path d="M26 0H0V26" fill="none" stroke="var(--grid)" strokeWidth=".65"/></pattern><pattern id="rack-vents" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M0 2h5" stroke="#698082" strokeWidth="1"/></pattern><filter id="shadow"><feDropShadow dx="0" dy="3" stdDeviation="4" floodOpacity=".12"/></filter></defs>
 <rect width="1050" height="660" fill="var(--floor)"/><rect x="60" y="66" width="930" height="540" rx="5" fill="url(#tiles)" stroke="var(--border)" strokeWidth="3"/>
 <path d="M58 150H40V505H58M993 150h17v355h-17" fill="none" stroke="var(--border)" strokeWidth="7"/>
 <text x="83" y="104" className="floor-note">{roomType.toUpperCase()} · FLOOR PLAN</text><text x="943" y="104" className="floor-note" textAnchor="end">N ↑</text>
 <rect x="112" y="303" width="820" height="61" rx="5" fill="var(--aisle)"/>
 <text x="522" y="338" textAnchor="middle" className="aisle-label">{roomType==='Data hall'?'C O L D  A I S L E':''}</text>
 {[150,258,366,474,582,690,798,906].map((x,i)=><text key={i} x={x} y="140" className="coordinate">{String(i+1).padStart(2,'0')}</text>)}
 {racks.map((r,i)=>{const ps=placements.filter(p=>p.rack_id===r.id),used=ps.reduce((a,p)=>a+p.height_u,0);const watts=ps.reduce((a,p)=>a+(assets.find(x=>x.id===p.asset_id)?.watts||0),0);const x=112+r.x*108,y=160+r.y*237;const active=selected.includes(r.id);const dim=search&&!ps.some(p=>assets.find(a=>a.id===p.asset_id)?.name.toLowerCase().includes(search.toLowerCase()))&&!r.label.toLowerCase().includes(search.toLowerCase());return <g key={r.id} role="button" tabIndex={0} aria-pressed={active} aria-label={`Rack ${r.label}, ${used} of ${r.height_u} U used`} onClick={e=>onSelect(r.id,e.ctrlKey||e.metaKey,e.shiftKey)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(r.id,e.ctrlKey||e.metaKey||e.key===' ',e.shiftKey)}}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();onDrop(r.id,e.dataTransfer.getData('text/plain'))}} opacity={dim?.25:1} className="rack-group">
 <rect x={x-5} y={y-5} width="88" height="137" rx="7" fill="none" stroke={active?'var(--accent)':'transparent'} strokeWidth="2.5"/>
 <rect x={x} y={y} width="78" height="127" rx="4" fill="var(--rack)" filter="url(#shadow)"/>
 <rect x={x+7} y={y+8} width="64" height="83" rx="2" fill="url(#rack-vents)"/>{active&&<g><rect x={x+59} y={y-8} width="20" height="20" rx="4" fill="var(--accent)"/><path d={`M${x+64} ${y+2}l4 4 7-8`} fill="none" stroke="white" strokeWidth="2"/></g>}
 <rect x={x+7} y={y+8} width="64" height="83" rx="2" fill={overlay==='heat'?['#429d86','#80ad84','#d6ac5c'][i%3]:active?'#208e7820':'transparent'} opacity={overlay==='heat'?.8:1}/>
 {[0,1,2,3].map(n=><circle key={n} cx={x+15+n*9} cy={y+99} r="1.7" fill={n===3?'#dbb775':'#52c9a3'}/>)}
 <text x={x+39} y={y+117} textAnchor="middle" className="rack-label">{r.label}</text>
 <text x={x+39} y={y+151} textAnchor="middle" className="rack-sub">{overlay==='heat'?`${(22.4+i*.23).toFixed(1)} °C`:overlay==='capacity'?`${used} / ${r.height_u} U`:`${(watts/1000).toFixed(1)} kW`}</text>
 {ghost?.rack_id===r.id&&<rect x={x-8} y={y-8} width="94" height="143" rx="8" className="ghost-outline"/>}
 </g>})}
 {(overlay==='power'||overlay==='network')&&<g className="flow-path"><path d="M93 565H946V520H154V286H911" stroke={overlay==='power'?'#d79b39':'#4e8ddb'} strokeWidth="4" fill="none" strokeDasharray="10 7"/><text x="90" y="591" className="floor-note">ILLUSTRATIVE {overlay.toUpperCase()} ROUTE · NOT LIVE FLOW</text></g>}
 <path d="M490 606v-22a42 42 0 0 1 42 42" fill="none" stroke="var(--border)" strokeWidth="2"/><text x="875" y="636" className="floor-note">0 ━━━━━ 5 m</text>
 </svg>;
}

export default function App(){
 const [screen,setScreen]=useState<'home'|'location'>('home');
 const [selectedRacks,setSelectedRacks]=useState<string[]>(['rack-00']),[multiSelect,setMultiSelect]=useState(false);
 const selectionAnchor=useRef('rack-00');
 const [role,setRole]=useState('operator'),[view,setView]=useState<View>('plan'),[room,setRoom]=useState('hall-a'),[rackId,setRackId]=useState('rack-00'),[assetId,setAssetId]=useState('asset-000');
 const [overlay,setOverlay]=useState<Overlay>('none'),[face,setFace]=useState<'front'|'rear'>('front'),[search,setSearch]=useState(''),[theme,setTheme]=useState(localStorage.getItem('unum-theme')||'light');
 const [reduced,setReduced]=useState(matchMedia('(prefers-reduced-motion: reduce)').matches),[queue,setQueue]=useState(false),[modules,setModules]=useState(false);
 const [ghost,setGhost]=useState<Ghost|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const {scene,assets,changes,sync,modules:moduleItems,status,refresh}=useOperationsData(role);
 const moveSubmission=useMemo(()=>createMoveSubmission(role),[role]);
 const refreshError=Object.values(status).map(s=>s.error).filter(Boolean).join(' · ');
 const lastFetch=status.placement.fetchedAt;
 const placementStale=!!status.placement.error||!lastFetch;
 const displayedError=[refreshError,error].filter(Boolean).join(' · ');
 useEffect(()=>{if(!ghost&&!queue&&!modules)return;const old=document.activeElement as HTMLElement|null;const dialog=document.querySelector<HTMLElement>('.move-dialog,.queue-drawer');const focusables=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex="0"]')||[]);focusables()[0]?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){setGhost(null);setQueue(false);setModules(false)}if(e.key==='Tab'){const f=focusables();if(!f.length)return;if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f[f.length-1].focus()}else if(!e.shiftKey&&document.activeElement===f[f.length-1]){e.preventDefault();f[0].focus()}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);old?.focus()}},[!!ghost,queue,modules]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('unum-theme',theme)},[theme]);
 useEffect(()=>{document.documentElement.dataset.motion=reduced?'reduced':'standard'},[reduced]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();document.querySelector<HTMLInputElement>('[aria-label="Search assets"]')?.focus()}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[]);
 const racks=useMemo(()=>scene?.racks.filter(r=>r.room_id===room)||[],[scene,room]);
 const rack=scene?.racks.find(r=>r.id===rackId),asset=assets.find(a=>a.id===assetId),placement=scene?.placements.find(p=>p.asset_id===assetId);
 const rackAssets=assets.filter(a=>scene?.placements.some(p=>p.asset_id===a.id&&selectedRacks.includes(p.rack_id)));
 const currentRoom=scene?.rooms.find(r=>r.id===room);
 const filteredAssets=rackAssets.filter(a=>`${a.name} ${a.asset_tag} ${a.model}`.toLowerCase().includes(search.toLowerCase()));
 const occupied=scene?.placements.filter(p=>racks.some(r=>r.id===p.rack_id)).reduce((n,p)=>n+p.height_u,0)||0;
 const pending=changes.filter(c=>c.state!=='completed').length,conflicts=sync?.conflicts.filter(c=>c.state==='conflict').length||0;
 const pendingChange=changes.find(c=>c.payload.asset_id===assetId&&!['completed','replan_required'].includes(c.state));
 const displayGhost=ghost||pendingChange?.payload||null;
 const ghostError=ghost&&scene?validateGhost(ghost,scene.racks,scene.placements):null;
 const selectRack=(id:string,toggle=false,range=false)=>{const next=cabinetSelection(selectedRacks,id,racks.map(r=>r.id),range?'range':toggle||multiSelect?'toggle':'replace',selectionAnchor.current);setSelectedRacks(next);if(!range)selectionAnchor.current=id;const primary=next.includes(id)?id:next[next.length-1]||'';setRackId(primary);const first=scene?.placements.find(p=>p.rack_id===primary);setAssetId(first?.asset_id||'')};
 const selectAsset=(id:string)=>{setAssetId(id);const p=scene?.placements.find(p=>p.asset_id===id);if(p){setRackId(p.rack_id);setSelectedRacks(old=>old.includes(p.rack_id)?old:[p.rack_id]);const r=scene?.racks.find(r=>r.id===p.rack_id);if(r)setRoom(r.room_id)}};
 const run=async(action:()=>Promise<unknown>,success:string)=>{setBusy(true);setError('');try{await action();setMessage(success);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const propose=()=>{if(!ghost||!scene)return;const p=scene.placements.find(x=>x.asset_id===ghost.asset_id);const a=assets.find(x=>x.id===ghost.asset_id);const authority=scene.authority.find(x=>x.site===a?.site);if(!p||!a||!authority)return;run(async()=>{await moveSubmission.submit({...ghost,expected_revision:p.revision,authority_epoch:authority.epoch,site:a.site});setGhost(null);setQueue(true)},'Move proposed. Confirmed placement is unchanged.')};
 const replan=(change:Change)=>{moveSubmission.reset();selectAsset(change.payload.asset_id);const destination=scene?.racks.find(r=>r.id===change.payload.rack_id);if(destination)setRoom(destination.room_id);setScreen('location');setQueue(false);setError('');setGhost({asset_id:change.payload.asset_id,rack_id:change.payload.rack_id,u:change.payload.u,face:change.payload.face});setMessage('Review the destination and submit a new proposal. A separate approval is required.');void refresh()};
 const selectRoom=(id:string)=>{setRoom(id);setSearch('');setView('plan');setMultiSelect(false);const r=scene?.racks.find(r=>r.room_id===id);setSelectedRacks(r?[r.id]:[]);setRackId(r?.id||'');selectionAnchor.current=r?.id||'';setAssetId(scene?.placements.find(p=>p.rack_id===r?.id)?.asset_id||'')};
 const openLocation=(id:string)=>{selectRoom(id);setScreen('location');setQueue(false);setModules(false)};
 return <div className="app-shell">
  <aside className="rail"><div className="brand-mark">u<span>•</span></div><button className="rail-button active" aria-label="Operations" onClick={()=>{setScreen('home');setQueue(false);setModules(false)}}><LayoutDashboard size={21}/></button><button className="rail-button" aria-label="Change queue" onClick={()=>setQueue(!queue)}><Workflow size={21}/></button><button className="rail-button" aria-label="Modules" onClick={()=>setModules(!modules)}><Layers size={21}/></button><div className="rail-bottom"><button className="rail-button" aria-label="Toggle theme" onClick={()=>setTheme(theme==='light'?'dark':'light')}><Sun size={20}/></button><span className="avatar">{role==='approver'?'JL':'AM'}</span></div></aside>
  <div className="workspace">
   <header className="topbar"><div className="wordmark">unum<span>DCIM</span><span className="product-label">OPERATIONS</span></div><div className="top-actions"><span className="demo-badge">SYNTHETIC DEMO</span><label className="role-select"><Users size={14}/><select aria-label="Demo operator identity" value={role} onChange={e=>setRole(e.target.value)}><option value="operator">Alex · Operator</option><option value="approver">Jordan · Approver</option><option value="admin">Admin · Platform</option></select></label><button className="icon-button" aria-label="Refresh data" onClick={refresh}><RefreshCw size={17}/></button></div></header>
   <div className="main-layout">{screen==='home'?<LocationsHome scene={scene} assets={assets} error={displayedError} onOpen={openLocation}/>:<>
    <aside className="navigator"><div className="nav-heading">EXPLORER <span>⌘ K</span></div><label className="search"><Search size={15}/><input placeholder="Find an asset or rack…" aria-label="Search assets" value={search} onChange={e=>setSearch(e.target.value)}/></label>{search&&<div className="global-results"><span className="eyebrow">MATCHING ASSETS</span>{assets.filter(a=>`${a.name} ${a.asset_tag} ${a.model}`.toLowerCase().includes(search.toLowerCase())).slice(0,20).map(a=><button key={a.id} onClick={()=>selectAsset(a.id)}><Cpu size={12}/>{a.name}</button>)}</div>}<div className="nav-section">ROOMS <span>{scene?.rooms.filter(r=>r.site===currentRoom?.site).length||0}</span></div><div className="site-label"><ChevronDown size={13}/><Grid2X2 size={15}/> {currentRoom?.site_name} <span className="site-dot"/></div><div className="room-tree">{scene?.rooms.filter(r=>r.site===currentRoom?.site).map(r=><button key={r.id} className={room===r.id?'selected':''} onClick={()=>selectRoom(r.id)}><Grid2X2 size={14}/>{r.name}<span>{scene.racks.filter(x=>x.room_id===r.id).length}</span></button>)}</div><div className="nav-divider"/><div className="nav-section">RACKS IN THIS ROOM <span>{racks.length}</span></div><div className="rack-list">{racks.map(r=><button key={r.id} className={selectedRacks.includes(r.id)?'selected':''} aria-pressed={selectedRacks.includes(r.id)} onClick={e=>selectRack(r.id,e.ctrlKey||e.metaKey,e.shiftKey)}><Server size={14}/><span>{r.label}</span><small>42U</small></button>)}</div><div className="navigator-footer"><ShieldCheck size={16}/><div>Site authority: local<small>Unum-owned work can continue offline</small></div></div></aside>
    <main className="operations">
     <div className="page-heading"><div><div className="breadcrumb"><button className="text-button" onClick={()=>setScreen('home')}>All locations</button> <ChevronRight size={12}/> {currentRoom?.site_name} <ChevronRight size={12}/> {scene?.rooms.find(r=>r.id===room)?.name||'Loading'}</div><h1>{scene?.rooms.find(r=>r.id===room)?.name||'Connecting to services…'}<span className="live-badge"><i/> {placementStale?"STALE DATA":"LOCAL DATA"}</span></h1><p>Plan with confidence. Keep every asset in view.</p></div><button className="button secondary" onClick={()=>setQueue(!queue)}><ArrowDownUp size={15}/> Changes <span className="count">{pending+conflicts}</span></button></div>
     {displayedError&&<div className="alert error" role="alert"><CloudOff size={16}/>{displayedError}{error&&<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={14}/></button>}</div>}
     {message&&<div className="alert success" role="status"><Check size={16}/>{message}<button aria-label="Dismiss notification" onClick={()=>setMessage('')}><X size={14}/></button></div>}
     <div className="stats"><div><span><Server size={15}/> RACKS</span><strong>{racks.length}<small>in this room</small></strong></div><div><span><Box size={15}/> SPACE USED</span><strong>{occupied}<small>/ {racks.length*42} U</small></strong><div className="mini-track"><i style={{width:`${occupied/(racks.length*42||1)*100}%`}}/></div></div><div><span><Zap size={15}/> NAMEPLATE POWER</span><strong>{(assets.filter(a=>scene?.placements.some(p=>p.asset_id===a.id&&racks.some(r=>r.id===p.rack_id))).reduce((n,a)=>n+a.watts,0)/1000).toFixed(1)}<small>kW · synthetic</small></strong></div><div><span><ArrowDownUp size={15}/> NLYTE CONNECTION</span><strong className="waiting">Not configured</strong><small>Live writes disabled</small></div></div>
     <section className="canvas-card"><div className="selection-toolbar"><label><input type="checkbox" checked={multiSelect} onChange={e=>setMultiSelect(e.target.checked)}/> Multi-select cabinets</label><span aria-live="polite">{selectedRacks.length} selected</span><button onClick={()=>{setSelectedRacks(racks.map(r=>r.id));if(!rackId&&racks[0]){setRackId(racks[0].id);setAssetId(scene?.placements.find(p=>p.rack_id===racks[0].id)?.asset_id||'')}}}>Select all</button><button onClick={()=>{setSelectedRacks([]);setRackId('');setAssetId('')}}>Clear</button><small>Ctrl/Cmd-click to toggle · Shift-click for a range</small></div><div className="canvas-toolbar"><div className="view-tabs">{([['plan',Grid2X2,'Floor plan'],['3d',Box,'3D view'],['elevation',Server,'Rack elevation']] as const).map(([v,Icon,name])=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}><Icon size={15}/>{name}</button>)}</div><div className="canvas-options">{view==='elevation'&&<select aria-label="Rack face" value={face} onChange={e=>setFace(e.target.value as 'front'|'rear')}><option value="front">Front</option><option value="rear">Rear</option></select>}<label><input type="checkbox" checked={reduced} onChange={e=>setReduced(e.target.checked)}/> Reduced effects</label><button title="Walkthrough: click scene, WASD to move, Escape to release" className={`icon-button ${view==='walk'?'chosen':''}`} aria-label="Walkthrough" onClick={()=>setView(view==='walk'?'plan':'walk')}><Maximize2 size={16}/></button></div></div>
      <div className={`canvas-area ${view==='elevation'?'elevation-area':''}`}>{!scene?<div className="empty"><Activity/>Connecting to placement service…</div>:view==='plan'?<FloorPlan roomType={currentRoom?roomTypeLabel(currentRoom):'Room'} racks={racks} placements={scene.placements} assets={assets} selected={selectedRacks} onSelect={selectRack} overlay={overlay} ghost={displayGhost} search={search} onDrop={(id,asset)=>{if(assets.some(a=>a.id===asset)){setGhost({asset_id:asset,rack_id:id,u:1,face:'front'});selectAsset(asset)}}}/>:view==='elevation'?<RackElevations racks={racks} selectedRackIds={selectedRacks} placements={scene.placements} assets={assets} selectedAsset={assetId} onSelectAsset={selectAsset} face={face} ghost={displayGhost}/>:<RenderBoundary><Suspense fallback={<div className="empty">Loading 3D renderer…</div>}><Twin3D key={view} racks={racks} selected={selectedRacks} onSelect={selectRack} overlay={overlay} reduced={reduced} walk={view==='walk'}/></Suspense></RenderBoundary>}
      {view!=='elevation'&&<div className="overlay-palette"><span>LAYERS</span>{([['none',Layers,'Default'],['capacity',Box,'Space'],['heat',Thermometer,'Heat'],['power',Zap,'Power'],['network',Network,'Network']] as const).map(([o,Icon,name])=><button key={o} onClick={()=>setOverlay(o)} className={overlay===o?'active':''}><Icon size={15}/>{name}</button>)}</div>}
      {view==='walk'&&<div className="overlay-notice">Click scene to walk · WASD · Esc releases cursor</div>}
      </div><div className="canvas-footer"><span><i className="legend-dot"/> Selected <i className="legend-dash"/> Proposed</span><span>{overlay==='heat'?'DEMO MEASUREMENT · illustrative values':overlay==='power'||overlay==='network'?'ILLUSTRATIVE TOPOLOGY · not live flow':`${racks.length} racks · dimensions are illustrative`}</span><span>{lastFetch?`${placementStale?'Last placement data':'Placement fetched'} ${new Date(lastFetch).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'Waiting for data'}</span></div>
     </section>
     <section className="asset-table"><div className="section-heading"><h2>{selectedRacks.length>1?`${selectedRacks.length} cabinets`:rack?.label||'No cabinets selected'} <span>Installed equipment</span></h2><span>{filteredAssets.length} assets · drag to propose a move</span></div><table><thead><tr><th>ASSET NAME</th><th>MODEL</th><th>POSITION</th><th>PLACEMENT OWNER</th></tr></thead><tbody>{filteredAssets.map(a=>{const p=scene?.placements.find(p=>p.asset_id===a.id);return <tr key={a.id} className={assetId===a.id?'selected':''} draggable onDragStart={e=>{e.dataTransfer.setData('text/plain',a.id);selectAsset(a.id)}} onClick={()=>selectAsset(a.id)}><td><button onClick={()=>selectAsset(a.id)}><Cpu size={15}/>{a.name}</button></td><td>{a.model}</td><td>{selectedRacks.length>1?`${scene?.racks.find(r=>r.id===p?.rack_id)?.label} · `:''}U{p?.u} <small>· {a.height_u}U</small></td><td><span className={`owner-tag ${p?.owner==='unum'?'native':''}`}>{p?.owner==='unum'?'UnumDCIM':'Nlyte'}</span></td></tr>})}</tbody></table></section>
    </main>
    <aside className="inspector"><div className="inspector-heading"><span>{selectedRacks.length>1?'CABINET SELECTION':'ASSET INSPECTOR'}</span><PanelRight size={16}/></div>{selectedRacks.length>1&&<div className="selection-summary"><span className="eyebrow">COMBINED VIEW</span><h2>{selectedRacks.length} cabinets selected</h2><p>{scene?.racks.filter(r=>selectedRacks.includes(r.id)).map(r=>r.label).join(' · ')}</p><dl><dt>Installed assets</dt><dd>{rackAssets.length}</dd><dt>Occupied space</dt><dd>{scene?.placements.filter(p=>selectedRacks.includes(p.rack_id)).reduce((n,p)=>n+p.height_u,0)} U</dd><dt>Nameplate power</dt><dd>{(rackAssets.reduce((n,a)=>n+a.watts,0)/1000).toFixed(1)} kW</dd></dl><small>Selection only. No placement changes are applied.</small></div>}{asset&&placement?<><div className="asset-hero"><div className="asset-icon"><Server size={30}/></div><span className="eyebrow">{asset.manufacturer} / {asset.height_u}U SERVER</span><h2>{asset.name}</h2><p>{asset.model}</p>{pendingChange&&<p className="state-badge">{label(pendingChange.state)}</p>}<span className="status-tag"><i/> In service</span></div><div className="inspector-tabs"><span className="active">Overview</span><button onClick={()=>setQueue(true)}>Changes</button></div><div className="detail-section"><h3>IDENTITY</h3><dl><dt>Asset tag</dt><dd>{asset.asset_tag}</dd><dt>Serial number</dt><dd>{asset.serial}</dd><dt>Lifecycle</dt><dd>{label(asset.lifecycle)}</dd></dl></div><div className="detail-section"><h3>PLACEMENT</h3><dl><dt>Rack</dt><dd>{scene?.racks.find(r=>r.id===placement.rack_id)?.label}</dd><dt>Position</dt><dd>U{placement.u} – U{placement.u+placement.height_u-1}</dd><dt>Face</dt><dd>{placement.face}</dd><dt>Revision</dt><dd>{placement.revision}</dd></dl></div><div className="ownership-card"><ShieldCheck size={17}/><div><strong>{placement.owner==='unum'?'UnumDCIM owns placement':'Nlyte owns placement'}</strong><p>{placement.owner==='unum'?'Local changes require separate approval.':'Proposed moves wait for Nlyte confirmation.'}</p></div></div><div className="detail-section"><h3>CAPACITY & CONNECTIONS</h3><dl><dt>Nameplate power</dt><dd>{asset.watts} W</dd><dt>Power trace</dt><dd><button className="text-button" onClick={()=>setOverlay('power')}>Demo route <ArrowRight size={12}/></button></dd><dt>Network trace</dt><dd><button className="text-button" onClick={()=>setOverlay('network')}>Demo route <ArrowRight size={12}/></button></dd></dl><small>Topology is synthetic. Live connectivity requires a verified source.</small></div><div className="inspector-actions"><button className="button primary" disabled={role==='approver'} onClick={()=>setGhost({asset_id:asset.id,rack_id:placement.rack_id,u:placement.u,face:placement.face})}><ArrowDownUp size={16}/> Propose rack move</button></div></>:<div className="empty">Select an asset to inspect.</div>}</aside></>}
   </div><footer className="statusbar"><span><span className="site-dot"/> Foundation v0.1.0 · independently running services</span><span><CloudOff size={12}/> Nlyte not connected · synthetic data only</span></footer>
  </div>
  {ghost&&<div className="modal-backdrop"><section className="move-dialog" role="dialog" aria-modal="true" aria-labelledby="move-title"><button className="close" aria-label="Close move proposal" onClick={()=>setGhost(null)}><X size={18}/></button><span className="eyebrow">PLACEMENT CHANGE</span><h2 id="move-title">Propose a rack move</h2><p>{assets.find(a=>a.id===ghost.asset_id)?.name} · Confirmed placement stays unchanged until execution.</p><label>Destination rack<select disabled={busy} value={ghost.rack_id} onChange={e=>setGhost({...ghost,rack_id:e.target.value})}>{racks.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label><div className="form-row"><label>Starting U<input disabled={busy} aria-label="Starting U" type="number" min="1" max="42" value={ghost.u} onChange={e=>setGhost({...ghost,u:Number(e.target.value)})}/></label><label>Face<select disabled={busy} value={ghost.face} onChange={e=>setGhost({...ghost,face:e.target.value as 'front'|'rear'})}><option value="front">Front</option><option value="rear">Rear</option></select></label></div><div className={`validation ${ghostError?'invalid':''}`}>{ghostError||'Local occupancy check passed. Server will revalidate reservations and authority.'}</div><div className="dialog-actions"><button className="button secondary" onClick={()=>{setGhost(null)}}>Cancel</button><button className="button primary" disabled={busy||!!ghostError} onClick={propose}>Submit proposal <ArrowRight size={15}/></button></div>{error&&<p role="alert" className="inline-error">{error}</p>}</section></div>}
  {queue&&<div className="drawer-backdrop"><section className="queue-drawer" aria-label="Change and conflict queue"><div className="drawer-header"><div><span className="eyebrow">CONTROLLED CHANGES</span><h2>Change queue</h2></div><button className="icon-button" aria-label="Close change queue" onClick={()=>setQueue(false)}><X/></button></div><p className="drawer-note">Demo identities are explicit: Alex proposes; Jordan approves. Nlyte writes are disabled.</p>{changes.length===0&&<div className="empty compact"><Workflow size={26}/>No proposed moves yet.</div>}{changes.map(c=><ChangeCard key={c.id} change={c} assetName={assets.find(a=>a.id===c.payload.asset_id)?.name||c.payload.asset_id} rackLabel={scene?.racks.find(r=>r.id===c.payload.rack_id)?.label||c.payload.rack_id} role={role} busy={busy} onReplan={()=>replan(c)} onApprove={()=>run(()=>api('workflow',`changes/${c.id}/approve`,role,{expected_revision:c.revision}),'Change approved by a separate principal.')} onExecute={()=>run(()=>api('workflow',`changes/${c.id}/execute`,role,{}),'Placement confirmed by the owning service.')}/>)}<div className="section-heading"><h2>Synchronization conflicts</h2><span>{conflicts} unresolved</span></div>{sync?.conflicts.map(c=><article className="change-card" key={c.id}><div><strong>{c.entity} / {label(c.field)}</strong><span className="state-badge conflict">{label(c.state)}</span></div><p>Owner: {c.owner} · Baseline: {String(c.baseline)}</p>{Object.entries(c.candidates).map(([connection,value])=><div className="candidate" key={connection}><span>{connection}<strong>{String(value)}</strong></span>{c.state==='conflict'&&<button disabled={busy||role==='approver'} onClick={()=>run(()=>api('synchronization',`conflicts/${c.id}/resolve`,role,{expected_revision:c.revision,candidate:connection}),'Resolution staged. Peer convergence has not been confirmed.')} className="button secondary">Stage this value</button>}</div>)}{c.state!=='conflict'&&<p className="drawer-note">Resolution recorded; remote write remains disabled.</p>}</article>)}</section></div>}
  {modules&&<div className="drawer-backdrop"><section className="queue-drawer"><div className="drawer-header"><div><span className="eyebrow">PLATFORM</span><h2>Module registry</h2></div><button className="icon-button" aria-label="Close modules" onClick={()=>setModules(false)}><X/></button></div><p className="drawer-note">Foundation services run independently. Planned modules are not represented as installed capabilities. Public plugin execution is disabled until isolation and signature verification pass.</p>{moduleItems.map(m=><div className="module-row" key={m.id}><Layers size={17}/><strong>{label(m.id)}</strong><span>{m.version}</span><span className={`owner-tag ${m.status==='implemented'?'native':''}`}>{m.status}</span></div>)}</section></div>}
 </div>;
}
