# Generated by Django 5.2.17 on 2026-09-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginGrant',
            fields=[
                ('plugin', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=100)),
                ('permissions', models.JSONField(default=list)),
                ('approved_by', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
