# Generated by Django 5.2.17 on 2026-09-13 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('baseline', models.JSONField(null=True)),
                ('candidates', models.JSONField()),
                ('state', models.CharField(default='conflict', max_length=40)),
                ('resolution', models.JSONField(null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('state', models.CharField(default='unconfigured', max_length=40)),
                ('capabilities', models.JSONField(default=dict)),
                ('last_success', models.DateTimeField(null=True)),
            ],
        ),
    ]
