# Generated by Django 5.2.17 on 2026-09-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=160)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('asset_tag', models.CharField(max_length=100)),
                ('height_u', models.PositiveIntegerField(default=2)),
                ('watts', models.PositiveIntegerField(default=400)),
                ('lifecycle', models.CharField(default='in_service', max_length=40)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
